# -*- coding: utf-8 -*-
"""Build the three block-adherence fixtures.

These are the fixtures behind the behavioural evidence in
`.advanced-plans/evidence/`. Until 2026-08-27 they lived in a session
scratchpad, which meant the proofs were narrative rather than re-derivable.
This module is that gap closed: run it and you get the same three projects the
rounds were measured on.

Three properties are deliberate, and each of them exists because a round found
it mattered.

R4  **The routing block is placed by the installer, never by hand.** Each
    project starts with an `AGENTS.md` and a `CLAUDE.md` containing only its own
    house rules; `tests/packaging/project_ops.py install` merges the block in.
    So the artefact under test is what a user would actually receive.

R1  **One fixture has a present-but-malformed manifest while every sentinel is
    genuinely on disk.** The block says a malformed manifest means treat every
    component as not installed. A reader that probes the filesystem instead gets
    this one wrong on all three requests. Every earlier fixture had a well-formed
    manifest, which is why six acceptance rounds could not catch the R1 defect.

    `broken-manifest` alone is not sufficient evidence, because `NONE`x3 is also
    what a runtime that never read the block produces. That is what the positive
    control is for -- see below.

--  **`all-installed` is the positive control, and it is also the only fixture
    where `gstack` and `gstack-to-plans` diverge** (true and false respectively).
    A fix that made every answer `NONE` would pass both negative fixtures and be
    worthless; and the gstack/gstack-to-plans split is what proves a runtime is
    reading per-component rather than per-vendor.

The manifest is generated by the project's own `.aaw/detect.py` run against a
**fake HOME**, so global tooling on the build machine cannot leak in and decide
the answer.

Usage
-----
    python tests/adherence/build_fixtures.py --out <dir>

Prints one JSON object per fixture describing what was built. `--out` defaults
to a `adherence-fixtures/` directory beside this file; it is removed and rebuilt.
Nothing is written inside the repository itself.
"""
import argparse
import datetime
import io
import json
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))

sys.path.insert(0, os.path.join(REPO, ".aaw"))
import detect as detect_mod  # noqa: E402

CLI = '''"""formatctl - render a record file into one of several output formats."""
import argparse
import sys

FORMATTERS = {"json": lambda r: str(r), "csv": lambda r: ",".join(r)}

def parse_args(argv):
    p = argparse.ArgumentParser(prog="formatctl")
    p.add_argument("path")
    p.add_argument("--format", choices=sorted(FORMATTERS), default="json")
    p.add_argument("--limit", type=int, default=0)
    return p.parse_args(argv)

def main(argv=None):
    args = parse_args(sys.argv[1:] if argv is None else argv)
    rows = [line.rstrip("\\n").split("\\t") for line in open(args.path)]
    if args.limit:
        rows = rows[: args.limit]
    render = FORMATTERS[args.format]
    for i, row in enumerate(rows):
        print("processing record %d of %d" % (i + 1, len(rows)), file=sys.stderr)
        print(render(row))
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
'''

README = """# formatctl

A small command-line tool that reads a tab-separated record file and renders it
as JSON or CSV. One module, `src/cli.py`. No tests yet.
"""

# The project's OWN instructions. The installer merges its block into this file;
# nothing below is written by the fixture builder after that point. The same text
# goes into CLAUDE.md, so claude and the AGENTS.md readers are compared on one
# instruction rather than on two files written for different audiences.
HOUSE_RULES = """# {title}

House rules for this repository.

- Keep `src/cli.py` importable without side effects.
- British spelling in prose, American in code identifiers.
- Never add a dependency without saying why in the commit message.
"""

# A self-contained skill body. It must tell the reader everything it needs and
# say explicitly not to look elsewhere: an earlier fixture's stub read "See the
# real copy; this is a sentinel only", which sent a worker out of the fixture and
# into a permission dialog. A stub that points outside itself is not a stub.
BRAINSTORMING = """---
name: brainstorming
description: Explore approaches and produce an approved design document before implementation.
---

# Brainstorming

Everything this skill needs is on this page. Do not look for another copy of it,
inside or outside this directory.

## When to use

A task needs a design decision before code can be written: several approaches are
plausible, or the shape of the answer is not yet settled.

## Procedure

1. **Classify the work** into exactly one of three paths and say which you chose:
   - **Spike** - the problem is not yet understood; the output is knowledge.
   - **Architectural** - the shape of the solution is the decision; the output is a design.
   - **Direct** - the approach is obvious; skip to implementation and say so.

2. **Explore at least two approaches** for a Spike or an Architectural task. For each,
   state what it costs and what it forecloses.

3. **Write the design document.** One file, in the location this project uses.
   It records the chosen approach, the alternatives rejected and why, and the
   constraints the implementation must honour.

4. **Present it for approval.** Say what the design commits the project to.

5. **Name the terminal step** - what happens after approval is granted.

## Default output location

`docs/superpowers/specs/<date>-<slug>.md`, unless project instructions name a
different location, in which case theirs wins.
"""

SPECS = [
    # gstack is GLOBAL here and advanced-planning is local, which is what makes
    # this fixture the only one where gstack and gstack-to-plans diverge.
    ("all-installed",
     dict(gstack=True, ap=True, sp=True, manifest="valid", decoy=False)),
    # The decoy: a .advanced-plans/ directory full of plausible spec content, in
    # a project where Advanced Planning is NOT installed. The block says a
    # directory is data, not an installation.
    ("only-superpowers",
     dict(gstack=False, ap=False, sp=True, manifest="valid", decoy=True)),
    # The discriminator.
    ("broken-manifest",
     dict(gstack=True, ap=True, sp=True, manifest="malformed", decoy=False)),
]


def _write(path, text):
    d = os.path.dirname(path)
    if d:
        os.makedirs(d, exist_ok=True)
    io.open(path, "w", encoding="utf-8", newline="\n").write(text)


def _block(path):
    t = io.open(path, encoding="utf-8", newline="").read()
    i = t.index("<!-- aaw-routing:begin -->")
    j = t.index("<!-- aaw-routing:end -->") + len("<!-- aaw-routing:end -->")
    return t[i:j]


def build(root, name, cfg):
    proj = os.path.join(root, name)
    home = os.path.join(root, "_home-" + name)
    for d in (proj, home):
        if os.path.isdir(d):
            shutil.rmtree(d)
        os.makedirs(d)

    _write(os.path.join(proj, "src", "cli.py"), CLI)
    _write(os.path.join(proj, "README.md"), README)
    _write(os.path.join(proj, "AGENTS.md"), HOUSE_RULES.format(title="AGENTS.md"))
    _write(os.path.join(proj, "CLAUDE.md"), HOUSE_RULES.format(title="CLAUDE.md"))

    if cfg["gstack"]:
        _write(os.path.join(home, ".claude", "skills", "gstack", "SKILL.md"),
               "---\nname: gstack\n---\n\ngstack, installed globally.\n")
    if cfg["ap"]:
        _write(os.path.join(proj, ".claude", "skills", "phase-plan-creator",
                            "SKILL.md"),
               "---\nname: phase-plan-creator\n---\n\nAdvanced Planning.\n")
        _write(os.path.join(proj, "VERSION"), "0.2.0\n")
    if cfg["sp"]:
        _write(os.path.join(proj, ".claude", "skills", "brainstorming",
                            "SKILL.md"), BRAINSTORMING)
    if cfg["decoy"]:
        _write(os.path.join(proj, ".advanced-plans", "specs", "borrowed.md"),
               "# A spec copied in from another project\n\n"
               "This directory is DATA. It was copied here with a template. "
               "Nothing installed it.\n")

    # --- manifest, from the project's own detector against the fake home -----
    res = detect_mod.detect(proj, home=home)
    comps = {}
    for key, row in res["components"].items():
        if row["installed"]:
            comps[key] = {k: row[k] for k in
                          ("installed", "scope", "install_path", "sentinel",
                           "version") if k in row}
        else:
            comps[key] = {"installed": False, "scope": "none"}
        if row.get("notes"):
            comps[key]["notes"] = row["notes"]
    comps["plannotator"] = {"installed": False, "scope": "none",
                            "deprecated": "2026-08-26",
                            "notes": "Deprecated by this programme."}
    manifest = {
        "schema_version": 1,
        "generated_at": datetime.datetime.now(datetime.timezone.utc)
                        .strftime("%Y-%m-%dT%H:%M:%SZ"),
        "generated_by": "setup-with-claude 0.2.0",
        "platform": detect_mod.platform_name(),
        "project_root": proj,
        "components": comps,
    }
    text = json.dumps(manifest, indent=2) + "\n"
    if cfg["manifest"] == "malformed":
        # Truncated mid-object: a valid-looking prefix, unparseable as a whole.
        text = text[: text.index('"components"') + 40] + "\n"
    _write(os.path.join(proj, ".aaw", "installed.json"), text)

    # --- the installer places the routing block, not this script ------------
    r = subprocess.run([sys.executable,
                        os.path.join(REPO, "tests", "packaging",
                                     "project_ops.py"),
                        "install", "--project", proj],
                       capture_output=True, text=True, cwd=REPO)

    agents_path = os.path.join(proj, "AGENTS.md")
    claude_path = os.path.join(proj, "CLAUDE.md")
    agents = io.open(agents_path, encoding="utf-8").read()
    claude = io.open(claude_path, encoding="utf-8").read()

    shutil.copyfile(os.path.join(HERE, "TASK.md"),
                    os.path.join(proj, "TASK.md"))

    out = dict(
        name=name,
        project=proj,
        home=home,
        install_exit=r.returncode,
        block_in_agents="<!-- aaw-routing:begin -->" in agents,
        block_in_claude="<!-- aaw-routing:begin -->" in claude,
        house_rules_kept=("British spelling in prose" in agents
                          and "British spelling in prose" in claude),
        manifest_state=cfg["manifest"],
        components={k: v["installed"] for k, v in comps.items()},
    )
    if out["block_in_agents"] and out["block_in_claude"]:
        # If these two differ, the runtimes are not being compared on the same
        # instruction and no cross-runtime claim can be made from the results.
        out["blocks_identical"] = _block(agents_path) == _block(claude_path)
        out["block_bytes"] = len(_block(agents_path))
    if r.returncode != 0:
        out["install_stderr"] = r.stderr.strip()[-800:]
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", default=os.path.join(HERE, "adherence-fixtures"),
                    help="directory to build into (removed and rebuilt)")
    args = ap.parse_args(argv)

    root = os.path.abspath(args.out)
    if os.path.commonpath([root, REPO]) == REPO and root != REPO:
        rel = os.path.relpath(root, REPO)
        if not rel.startswith("tests" + os.sep):
            ap.error("refusing to build inside the repository at %s" % rel)
    if os.path.isdir(root):
        shutil.rmtree(root)
    os.makedirs(root)

    ok = True
    for name, cfg in SPECS:
        out = build(root, name, cfg)
        print(json.dumps(out, indent=2))
        if out["install_exit"] != 0 or not out.get("blocks_identical"):
            ok = False
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
